### ISSUE TITLE
Error compiling npm run build.

### ISSUE THREAD

**Issue by VeLuisS** [leephan2k1/manga-app#5]
Error compiling npm run build.
Help, I leave below the result of the terminal.

`
[  ==] info  - Generating static pages (9/11)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot destructure property 'comics' of 'resultAll' as it is null.
    at getStaticProps (/.next/server/pages/index.js:1183:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async renderToHTML (/node_modules/next/dist/server/render.js:386:20)
    at async /node_modules/next/dist/export/worker.js:304:36
    at async Span.traceAsyncFn (/node_modules/next/dist/trace/trace.js:79:20)
info  - Generating static pages (11/11)

> Build error occurred
Error: Export encountered errors on following paths:
	/
    at /node_modules/next/dist/export/index.js:404:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/node_modules/next/dist/trace/trace.js:79:20)
    at async /node_modules/next/dist/build/index.js:1229:21
    at async Span.traceAsyncFn (/node_modules/next/dist/trace/trace.js:79:20)
    at async /node_modules/next/dist/build/index.js:1091:17
    at async Span.traceAsyncFn (/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/node_modules/next/dist/build/index.js:65:29)
`

**Comment by leephan2k1** [comment]
You need setup [this database](https://github.com/leephan2k1/manga-app/releases/tag/v0.2) to connect to the project, if you did, skip it

Maybe you need to add a collection "real_time_comics" to MongoDB with data: [json data](https://www.mediafire.com/file/5jj2howwzyiqsmm/real_time_comics.json/file) . 

if you need to work it's ok. Since this data will be outdated (Because this collection generate by cron-job server from the repo: [kyt-server](https://github.com/leephan2k1/kyoto-manga-server).) so I do not add it to the sample data. But I think there is an error so I will add this collection to the sample database in the future :b

**Comment by VeLuisS** [comment]
Hi, thanks a lot for the timely response, I'll try to add a table to the MongoDB database and try to compile again.

**Comment by VeLuisS** [comment]
Sorry for the question, but does this code have no Backend?

PD: The additional Json to the database provided, if I fix the problem.  I managed to install successfully.  Test and be delighted.  Thanks for this project.

**Comment by leephan2k1** [comment]
Not really, this repo has no backend (It includes in [/src/serverless](https://github.com/leephan2k1/manga-app/tree/main/src/serverless) and [NextJS's API routes](https://github.com/leephan2k1/manga-app/tree/main/src/pages/api).). 
But the server code doesn't do many tasks.

I have a separate [backend ](https://github.com/leephan2k1/kyoto-manga-server) to handle cron-job data updates and the Socket server. 

Finally, I'd like to thank you for your interest in my project
